name: Initial Leetcode Bulk Sync

on:
  workflow_dispatch: # This allows you to trigger the bulk sync manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-id: "0" # Forces it to sync everything back to your first problem
